// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: favorites_updated_event.proto

package com.wine.to.up.user.service.api.message;

public final class FavoritesUpdatedEventOuterClass {
  private FavoritesUpdatedEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FavoritesUpdatedEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FavoritesUpdatedEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 userId = 1;</code>
     */
    long getUserId();

    /**
     * <code>optional string wineId = 2;</code>
     */
    java.lang.String getWineId();
    /**
     * <code>optional string wineId = 2;</code>
     */
    com.google.protobuf.ByteString
        getWineIdBytes();

    /**
     * <code>optional .EntityUpdatedMeta meta = 3;</code>
     */
    boolean hasMeta();
    /**
     * <code>optional .EntityUpdatedMeta meta = 3;</code>
     */
    com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta getMeta();
    /**
     * <code>optional .EntityUpdatedMeta meta = 3;</code>
     */
    com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMetaOrBuilder getMetaOrBuilder();
  }
  /**
   * Protobuf type {@code FavoritesUpdatedEvent}
   */
  public  static final class FavoritesUpdatedEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FavoritesUpdatedEvent)
      FavoritesUpdatedEventOrBuilder {
    // Use FavoritesUpdatedEvent.newBuilder() to construct.
    private FavoritesUpdatedEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FavoritesUpdatedEvent() {
      userId_ = 0L;
      wineId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FavoritesUpdatedEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              wineId_ = s;
              break;
            }
            case 26: {
              com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta.Builder subBuilder = null;
              if (meta_ != null) {
                subBuilder = meta_.toBuilder();
              }
              meta_ = input.readMessage(com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(meta_);
                meta_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.internal_static_FavoritesUpdatedEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.internal_static_FavoritesUpdatedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent.class, com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>optional int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int WINEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object wineId_;
    /**
     * <code>optional string wineId = 2;</code>
     */
    public java.lang.String getWineId() {
      java.lang.Object ref = wineId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wineId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string wineId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWineIdBytes() {
      java.lang.Object ref = wineId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wineId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int META_FIELD_NUMBER = 3;
    private com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta meta_;
    /**
     * <code>optional .EntityUpdatedMeta meta = 3;</code>
     */
    public boolean hasMeta() {
      return meta_ != null;
    }
    /**
     * <code>optional .EntityUpdatedMeta meta = 3;</code>
     */
    public com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta getMeta() {
      return meta_ == null ? com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta.getDefaultInstance() : meta_;
    }
    /**
     * <code>optional .EntityUpdatedMeta meta = 3;</code>
     */
    public com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMetaOrBuilder getMetaOrBuilder() {
      return getMeta();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (!getWineIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, wineId_);
      }
      if (meta_ != null) {
        output.writeMessage(3, getMeta());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (!getWineIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, wineId_);
      }
      if (meta_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMeta());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent)) {
        return super.equals(obj);
      }
      com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent other = (com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getWineId()
          .equals(other.getWineId());
      result = result && (hasMeta() == other.hasMeta());
      if (hasMeta()) {
        result = result && getMeta()
            .equals(other.getMeta());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + WINEID_FIELD_NUMBER;
      hash = (53 * hash) + getWineId().hashCode();
      if (hasMeta()) {
        hash = (37 * hash) + META_FIELD_NUMBER;
        hash = (53 * hash) + getMeta().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FavoritesUpdatedEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FavoritesUpdatedEvent)
        com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.internal_static_FavoritesUpdatedEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.internal_static_FavoritesUpdatedEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent.class, com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent.Builder.class);
      }

      // Construct using com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        wineId_ = "";

        if (metaBuilder_ == null) {
          meta_ = null;
        } else {
          meta_ = null;
          metaBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.internal_static_FavoritesUpdatedEvent_descriptor;
      }

      public com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent getDefaultInstanceForType() {
        return com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent.getDefaultInstance();
      }

      public com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent build() {
        com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent buildPartial() {
        com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent result = new com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent(this);
        result.userId_ = userId_;
        result.wineId_ = wineId_;
        if (metaBuilder_ == null) {
          result.meta_ = meta_;
        } else {
          result.meta_ = metaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent) {
          return mergeFrom((com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent other) {
        if (other == com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getWineId().isEmpty()) {
          wineId_ = other.wineId_;
          onChanged();
        }
        if (other.hasMeta()) {
          mergeMeta(other.getMeta());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object wineId_ = "";
      /**
       * <code>optional string wineId = 2;</code>
       */
      public java.lang.String getWineId() {
        java.lang.Object ref = wineId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          wineId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string wineId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getWineIdBytes() {
        java.lang.Object ref = wineId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wineId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string wineId = 2;</code>
       */
      public Builder setWineId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        wineId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string wineId = 2;</code>
       */
      public Builder clearWineId() {
        
        wineId_ = getDefaultInstance().getWineId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string wineId = 2;</code>
       */
      public Builder setWineIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        wineId_ = value;
        onChanged();
        return this;
      }

      private com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta meta_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta, com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta.Builder, com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMetaOrBuilder> metaBuilder_;
      /**
       * <code>optional .EntityUpdatedMeta meta = 3;</code>
       */
      public boolean hasMeta() {
        return metaBuilder_ != null || meta_ != null;
      }
      /**
       * <code>optional .EntityUpdatedMeta meta = 3;</code>
       */
      public com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta getMeta() {
        if (metaBuilder_ == null) {
          return meta_ == null ? com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta.getDefaultInstance() : meta_;
        } else {
          return metaBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .EntityUpdatedMeta meta = 3;</code>
       */
      public Builder setMeta(com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          meta_ = value;
          onChanged();
        } else {
          metaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .EntityUpdatedMeta meta = 3;</code>
       */
      public Builder setMeta(
          com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          meta_ = builderForValue.build();
          onChanged();
        } else {
          metaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .EntityUpdatedMeta meta = 3;</code>
       */
      public Builder mergeMeta(com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta value) {
        if (metaBuilder_ == null) {
          if (meta_ != null) {
            meta_ =
              com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta.newBuilder(meta_).mergeFrom(value).buildPartial();
          } else {
            meta_ = value;
          }
          onChanged();
        } else {
          metaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .EntityUpdatedMeta meta = 3;</code>
       */
      public Builder clearMeta() {
        if (metaBuilder_ == null) {
          meta_ = null;
          onChanged();
        } else {
          meta_ = null;
          metaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .EntityUpdatedMeta meta = 3;</code>
       */
      public com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta.Builder getMetaBuilder() {
        
        onChanged();
        return getMetaFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .EntityUpdatedMeta meta = 3;</code>
       */
      public com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMetaOrBuilder getMetaOrBuilder() {
        if (metaBuilder_ != null) {
          return metaBuilder_.getMessageOrBuilder();
        } else {
          return meta_ == null ?
              com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta.getDefaultInstance() : meta_;
        }
      }
      /**
       * <code>optional .EntityUpdatedMeta meta = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta, com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta.Builder, com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMetaOrBuilder> 
          getMetaFieldBuilder() {
        if (metaBuilder_ == null) {
          metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta, com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMeta.Builder, com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.EntityUpdatedMetaOrBuilder>(
                  getMeta(),
                  getParentForChildren(),
                  isClean());
          meta_ = null;
        }
        return metaBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:FavoritesUpdatedEvent)
    }

    // @@protoc_insertion_point(class_scope:FavoritesUpdatedEvent)
    private static final com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent();
    }

    public static com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FavoritesUpdatedEvent>
        PARSER = new com.google.protobuf.AbstractParser<FavoritesUpdatedEvent>() {
      public FavoritesUpdatedEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FavoritesUpdatedEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FavoritesUpdatedEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FavoritesUpdatedEvent> getParserForType() {
      return PARSER;
    }

    public com.wine.to.up.user.service.api.message.FavoritesUpdatedEventOuterClass.FavoritesUpdatedEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FavoritesUpdatedEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FavoritesUpdatedEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035favorites_updated_event.proto\032\031entity_" +
      "updated_meta.proto\"Y\n\025FavoritesUpdatedEv" +
      "ent\022\016\n\006userId\030\001 \001(\003\022\016\n\006wineId\030\002 \001(\t\022 \n\004m" +
      "eta\030\003 \001(\0132\022.EntityUpdatedMetaB)\n\'com.win" +
      "e.to.up.user.service.api.messageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.getDescriptor(),
        }, assigner);
    internal_static_FavoritesUpdatedEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FavoritesUpdatedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FavoritesUpdatedEvent_descriptor,
        new java.lang.String[] { "UserId", "WineId", "Meta", });
    com.wine.to.up.user.service.api.message.EntityUpdatedMetaOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
