// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: new_user_created_event.proto

package com.wine.to.up.user.service.api.message;

public final class NewUserCreatedEventOuterClass {
  private NewUserCreatedEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NewUserCreatedEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NewUserCreatedEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 userId = 1;</code>
     */
    long getUserId();

    /**
     * <code>optional string phoneNumber = 2;</code>
     */
    java.lang.String getPhoneNumber();
    /**
     * <code>optional string phoneNumber = 2;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes();

    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string birthdate = 4;</code>
     */
    java.lang.String getBirthdate();
    /**
     * <code>optional string birthdate = 4;</code>
     */
    com.google.protobuf.ByteString
        getBirthdateBytes();

    /**
     * <code>optional int64 cityId = 5;</code>
     */
    long getCityId();
  }
  /**
   * Protobuf type {@code NewUserCreatedEvent}
   */
  public  static final class NewUserCreatedEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NewUserCreatedEvent)
      NewUserCreatedEventOrBuilder {
    // Use NewUserCreatedEvent.newBuilder() to construct.
    private NewUserCreatedEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NewUserCreatedEvent() {
      userId_ = 0L;
      phoneNumber_ = "";
      name_ = "";
      birthdate_ = "";
      cityId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NewUserCreatedEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneNumber_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              birthdate_ = s;
              break;
            }
            case 40: {

              cityId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.internal_static_NewUserCreatedEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.internal_static_NewUserCreatedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent.class, com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>optional int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 2;
    private volatile java.lang.Object phoneNumber_;
    /**
     * <code>optional string phoneNumber = 2;</code>
     */
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      }
    }
    /**
     * <code>optional string phoneNumber = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTHDATE_FIELD_NUMBER = 4;
    private volatile java.lang.Object birthdate_;
    /**
     * <code>optional string birthdate = 4;</code>
     */
    public java.lang.String getBirthdate() {
      java.lang.Object ref = birthdate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthdate_ = s;
        return s;
      }
    }
    /**
     * <code>optional string birthdate = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBirthdateBytes() {
      java.lang.Object ref = birthdate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITYID_FIELD_NUMBER = 5;
    private long cityId_;
    /**
     * <code>optional int64 cityId = 5;</code>
     */
    public long getCityId() {
      return cityId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, phoneNumber_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getBirthdateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, birthdate_);
      }
      if (cityId_ != 0L) {
        output.writeInt64(5, cityId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, phoneNumber_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getBirthdateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, birthdate_);
      }
      if (cityId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, cityId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent)) {
        return super.equals(obj);
      }
      com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent other = (com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getPhoneNumber()
          .equals(other.getPhoneNumber());
      result = result && getName()
          .equals(other.getName());
      result = result && getBirthdate()
          .equals(other.getBirthdate());
      result = result && (getCityId()
          == other.getCityId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthdate().hashCode();
      hash = (37 * hash) + CITYID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCityId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NewUserCreatedEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NewUserCreatedEvent)
        com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.internal_static_NewUserCreatedEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.internal_static_NewUserCreatedEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent.class, com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent.Builder.class);
      }

      // Construct using com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        phoneNumber_ = "";

        name_ = "";

        birthdate_ = "";

        cityId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.internal_static_NewUserCreatedEvent_descriptor;
      }

      public com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent getDefaultInstanceForType() {
        return com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent.getDefaultInstance();
      }

      public com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent build() {
        com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent buildPartial() {
        com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent result = new com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent(this);
        result.userId_ = userId_;
        result.phoneNumber_ = phoneNumber_;
        result.name_ = name_;
        result.birthdate_ = birthdate_;
        result.cityId_ = cityId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent) {
          return mergeFrom((com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent other) {
        if (other == com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getPhoneNumber().isEmpty()) {
          phoneNumber_ = other.phoneNumber_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getBirthdate().isEmpty()) {
          birthdate_ = other.birthdate_;
          onChanged();
        }
        if (other.getCityId() != 0L) {
          setCityId(other.getCityId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object phoneNumber_ = "";
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public java.lang.String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public Builder setPhoneNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public Builder clearPhoneNumber() {
        
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public Builder setPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneNumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object birthdate_ = "";
      /**
       * <code>optional string birthdate = 4;</code>
       */
      public java.lang.String getBirthdate() {
        java.lang.Object ref = birthdate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          birthdate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string birthdate = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBirthdateBytes() {
        java.lang.Object ref = birthdate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthdate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string birthdate = 4;</code>
       */
      public Builder setBirthdate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        birthdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string birthdate = 4;</code>
       */
      public Builder clearBirthdate() {
        
        birthdate_ = getDefaultInstance().getBirthdate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string birthdate = 4;</code>
       */
      public Builder setBirthdateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        birthdate_ = value;
        onChanged();
        return this;
      }

      private long cityId_ ;
      /**
       * <code>optional int64 cityId = 5;</code>
       */
      public long getCityId() {
        return cityId_;
      }
      /**
       * <code>optional int64 cityId = 5;</code>
       */
      public Builder setCityId(long value) {
        
        cityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cityId = 5;</code>
       */
      public Builder clearCityId() {
        
        cityId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:NewUserCreatedEvent)
    }

    // @@protoc_insertion_point(class_scope:NewUserCreatedEvent)
    private static final com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent();
    }

    public static com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NewUserCreatedEvent>
        PARSER = new com.google.protobuf.AbstractParser<NewUserCreatedEvent>() {
      public NewUserCreatedEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NewUserCreatedEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NewUserCreatedEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NewUserCreatedEvent> getParserForType() {
      return PARSER;
    }

    public com.wine.to.up.user.service.api.message.NewUserCreatedEventOuterClass.NewUserCreatedEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewUserCreatedEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewUserCreatedEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034new_user_created_event.proto\"k\n\023NewUse" +
      "rCreatedEvent\022\016\n\006userId\030\001 \001(\003\022\023\n\013phoneNu" +
      "mber\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\021\n\tbirthdate\030\004 " +
      "\001(\t\022\016\n\006cityId\030\005 \001(\003B)\n\'com.wine.to.up.us" +
      "er.service.api.messageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NewUserCreatedEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NewUserCreatedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewUserCreatedEvent_descriptor,
        new java.lang.String[] { "UserId", "PhoneNumber", "Name", "Birthdate", "CityId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
