// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_tokens.proto

package com.wine.to.up.user.service.api.message;

public final class UserTokensOuterClass {
  private UserTokensOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserTokensOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserTokens)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 userId = 1;</code>
     */
    long getUserId();

    /**
     * <code>repeated string iosTokens = 2;</code>
     */
    java.util.List<java.lang.String>
        getIosTokensList();
    /**
     * <code>repeated string iosTokens = 2;</code>
     */
    int getIosTokensCount();
    /**
     * <code>repeated string iosTokens = 2;</code>
     */
    java.lang.String getIosTokens(int index);
    /**
     * <code>repeated string iosTokens = 2;</code>
     */
    com.google.protobuf.ByteString
        getIosTokensBytes(int index);

    /**
     * <code>repeated string fcmTokens = 3;</code>
     */
    java.util.List<java.lang.String>
        getFcmTokensList();
    /**
     * <code>repeated string fcmTokens = 3;</code>
     */
    int getFcmTokensCount();
    /**
     * <code>repeated string fcmTokens = 3;</code>
     */
    java.lang.String getFcmTokens(int index);
    /**
     * <code>repeated string fcmTokens = 3;</code>
     */
    com.google.protobuf.ByteString
        getFcmTokensBytes(int index);
  }
  /**
   * Protobuf type {@code UserTokens}
   */
  public  static final class UserTokens extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserTokens)
      UserTokensOrBuilder {
    // Use UserTokens.newBuilder() to construct.
    private UserTokens(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserTokens() {
      userId_ = 0L;
      iosTokens_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      fcmTokens_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserTokens(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                iosTokens_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              iosTokens_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                fcmTokens_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              fcmTokens_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          iosTokens_ = iosTokens_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          fcmTokens_ = fcmTokens_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wine.to.up.user.service.api.message.UserTokensOuterClass.internal_static_UserTokens_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wine.to.up.user.service.api.message.UserTokensOuterClass.internal_static_UserTokens_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.class, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder.class);
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>optional int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int IOSTOKENS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList iosTokens_;
    /**
     * <code>repeated string iosTokens = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIosTokensList() {
      return iosTokens_;
    }
    /**
     * <code>repeated string iosTokens = 2;</code>
     */
    public int getIosTokensCount() {
      return iosTokens_.size();
    }
    /**
     * <code>repeated string iosTokens = 2;</code>
     */
    public java.lang.String getIosTokens(int index) {
      return iosTokens_.get(index);
    }
    /**
     * <code>repeated string iosTokens = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIosTokensBytes(int index) {
      return iosTokens_.getByteString(index);
    }

    public static final int FCMTOKENS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList fcmTokens_;
    /**
     * <code>repeated string fcmTokens = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFcmTokensList() {
      return fcmTokens_;
    }
    /**
     * <code>repeated string fcmTokens = 3;</code>
     */
    public int getFcmTokensCount() {
      return fcmTokens_.size();
    }
    /**
     * <code>repeated string fcmTokens = 3;</code>
     */
    public java.lang.String getFcmTokens(int index) {
      return fcmTokens_.get(index);
    }
    /**
     * <code>repeated string fcmTokens = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFcmTokensBytes(int index) {
      return fcmTokens_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      for (int i = 0; i < iosTokens_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, iosTokens_.getRaw(i));
      }
      for (int i = 0; i < fcmTokens_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fcmTokens_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < iosTokens_.size(); i++) {
          dataSize += computeStringSizeNoTag(iosTokens_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIosTokensList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fcmTokens_.size(); i++) {
          dataSize += computeStringSizeNoTag(fcmTokens_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFcmTokensList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens)) {
        return super.equals(obj);
      }
      com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens other = (com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getIosTokensList()
          .equals(other.getIosTokensList());
      result = result && getFcmTokensList()
          .equals(other.getFcmTokensList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      if (getIosTokensCount() > 0) {
        hash = (37 * hash) + IOSTOKENS_FIELD_NUMBER;
        hash = (53 * hash) + getIosTokensList().hashCode();
      }
      if (getFcmTokensCount() > 0) {
        hash = (37 * hash) + FCMTOKENS_FIELD_NUMBER;
        hash = (53 * hash) + getFcmTokensList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserTokens}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserTokens)
        com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokensOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wine.to.up.user.service.api.message.UserTokensOuterClass.internal_static_UserTokens_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wine.to.up.user.service.api.message.UserTokensOuterClass.internal_static_UserTokens_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.class, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder.class);
      }

      // Construct using com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        iosTokens_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        fcmTokens_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wine.to.up.user.service.api.message.UserTokensOuterClass.internal_static_UserTokens_descriptor;
      }

      public com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens getDefaultInstanceForType() {
        return com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.getDefaultInstance();
      }

      public com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens build() {
        com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens buildPartial() {
        com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens result = new com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.userId_ = userId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          iosTokens_ = iosTokens_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.iosTokens_ = iosTokens_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          fcmTokens_ = fcmTokens_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.fcmTokens_ = fcmTokens_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens) {
          return mergeFrom((com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens other) {
        if (other == com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.iosTokens_.isEmpty()) {
          if (iosTokens_.isEmpty()) {
            iosTokens_ = other.iosTokens_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureIosTokensIsMutable();
            iosTokens_.addAll(other.iosTokens_);
          }
          onChanged();
        }
        if (!other.fcmTokens_.isEmpty()) {
          if (fcmTokens_.isEmpty()) {
            fcmTokens_ = other.fcmTokens_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFcmTokensIsMutable();
            fcmTokens_.addAll(other.fcmTokens_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList iosTokens_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIosTokensIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          iosTokens_ = new com.google.protobuf.LazyStringArrayList(iosTokens_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string iosTokens = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getIosTokensList() {
        return iosTokens_.getUnmodifiableView();
      }
      /**
       * <code>repeated string iosTokens = 2;</code>
       */
      public int getIosTokensCount() {
        return iosTokens_.size();
      }
      /**
       * <code>repeated string iosTokens = 2;</code>
       */
      public java.lang.String getIosTokens(int index) {
        return iosTokens_.get(index);
      }
      /**
       * <code>repeated string iosTokens = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIosTokensBytes(int index) {
        return iosTokens_.getByteString(index);
      }
      /**
       * <code>repeated string iosTokens = 2;</code>
       */
      public Builder setIosTokens(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIosTokensIsMutable();
        iosTokens_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string iosTokens = 2;</code>
       */
      public Builder addIosTokens(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIosTokensIsMutable();
        iosTokens_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string iosTokens = 2;</code>
       */
      public Builder addAllIosTokens(
          java.lang.Iterable<java.lang.String> values) {
        ensureIosTokensIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, iosTokens_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string iosTokens = 2;</code>
       */
      public Builder clearIosTokens() {
        iosTokens_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string iosTokens = 2;</code>
       */
      public Builder addIosTokensBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureIosTokensIsMutable();
        iosTokens_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList fcmTokens_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFcmTokensIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          fcmTokens_ = new com.google.protobuf.LazyStringArrayList(fcmTokens_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string fcmTokens = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFcmTokensList() {
        return fcmTokens_.getUnmodifiableView();
      }
      /**
       * <code>repeated string fcmTokens = 3;</code>
       */
      public int getFcmTokensCount() {
        return fcmTokens_.size();
      }
      /**
       * <code>repeated string fcmTokens = 3;</code>
       */
      public java.lang.String getFcmTokens(int index) {
        return fcmTokens_.get(index);
      }
      /**
       * <code>repeated string fcmTokens = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFcmTokensBytes(int index) {
        return fcmTokens_.getByteString(index);
      }
      /**
       * <code>repeated string fcmTokens = 3;</code>
       */
      public Builder setFcmTokens(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFcmTokensIsMutable();
        fcmTokens_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fcmTokens = 3;</code>
       */
      public Builder addFcmTokens(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFcmTokensIsMutable();
        fcmTokens_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fcmTokens = 3;</code>
       */
      public Builder addAllFcmTokens(
          java.lang.Iterable<java.lang.String> values) {
        ensureFcmTokensIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fcmTokens_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fcmTokens = 3;</code>
       */
      public Builder clearFcmTokens() {
        fcmTokens_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fcmTokens = 3;</code>
       */
      public Builder addFcmTokensBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFcmTokensIsMutable();
        fcmTokens_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UserTokens)
    }

    // @@protoc_insertion_point(class_scope:UserTokens)
    private static final com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens();
    }

    public static com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserTokens>
        PARSER = new com.google.protobuf.AbstractParser<UserTokens>() {
      public UserTokens parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserTokens(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserTokens> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserTokens> getParserForType() {
      return PARSER;
    }

    public com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserTokens_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserTokens_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021user_tokens.proto\"B\n\nUserTokens\022\016\n\006use" +
      "rId\030\001 \001(\003\022\021\n\tiosTokens\030\002 \003(\t\022\021\n\tfcmToken" +
      "s\030\003 \003(\tB)\n\'com.wine.to.up.user.service.a" +
      "pi.messageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserTokens_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserTokens_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserTokens_descriptor,
        new java.lang.String[] { "UserId", "IosTokens", "FcmTokens", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
