// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wine_price_updated_with_tokens_event.proto

package com.wine.to.up.user.service.api.message;

public final class WinePriceUpdatedWithTokensEventOuterClass {
  private WinePriceUpdatedWithTokensEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WinePriceUpdatedWithTokensEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WinePriceUpdatedWithTokensEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string wineId = 1;</code>
     */
    java.lang.String getWineId();
    /**
     * <code>optional string wineId = 1;</code>
     */
    com.google.protobuf.ByteString
        getWineIdBytes();

    /**
     * <code>optional string wineName = 2;</code>
     */
    java.lang.String getWineName();
    /**
     * <code>optional string wineName = 2;</code>
     */
    com.google.protobuf.ByteString
        getWineNameBytes();

    /**
     * <code>optional float newWinePrice = 3;</code>
     */
    float getNewWinePrice();

    /**
     * <code>repeated .UserTokens userTokens = 4;</code>
     */
    java.util.List<com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens> 
        getUserTokensList();
    /**
     * <code>repeated .UserTokens userTokens = 4;</code>
     */
    com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens getUserTokens(int index);
    /**
     * <code>repeated .UserTokens userTokens = 4;</code>
     */
    int getUserTokensCount();
    /**
     * <code>repeated .UserTokens userTokens = 4;</code>
     */
    java.util.List<? extends com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokensOrBuilder> 
        getUserTokensOrBuilderList();
    /**
     * <code>repeated .UserTokens userTokens = 4;</code>
     */
    com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokensOrBuilder getUserTokensOrBuilder(
        int index);
  }
  /**
   * <pre>
   *event that indicates that message was sent to kafka
   * </pre>
   *
   * Protobuf type {@code WinePriceUpdatedWithTokensEvent}
   */
  public  static final class WinePriceUpdatedWithTokensEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WinePriceUpdatedWithTokensEvent)
      WinePriceUpdatedWithTokensEventOrBuilder {
    // Use WinePriceUpdatedWithTokensEvent.newBuilder() to construct.
    private WinePriceUpdatedWithTokensEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WinePriceUpdatedWithTokensEvent() {
      wineId_ = "";
      wineName_ = "";
      newWinePrice_ = 0F;
      userTokens_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WinePriceUpdatedWithTokensEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              wineId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              wineName_ = s;
              break;
            }
            case 29: {

              newWinePrice_ = input.readFloat();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                userTokens_ = new java.util.ArrayList<com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens>();
                mutable_bitField0_ |= 0x00000008;
              }
              userTokens_.add(
                  input.readMessage(com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          userTokens_ = java.util.Collections.unmodifiableList(userTokens_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.internal_static_WinePriceUpdatedWithTokensEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.internal_static_WinePriceUpdatedWithTokensEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent.class, com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent.Builder.class);
    }

    private int bitField0_;
    public static final int WINEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object wineId_;
    /**
     * <code>optional string wineId = 1;</code>
     */
    public java.lang.String getWineId() {
      java.lang.Object ref = wineId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wineId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string wineId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWineIdBytes() {
      java.lang.Object ref = wineId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wineId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WINENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object wineName_;
    /**
     * <code>optional string wineName = 2;</code>
     */
    public java.lang.String getWineName() {
      java.lang.Object ref = wineName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wineName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string wineName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWineNameBytes() {
      java.lang.Object ref = wineName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wineName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEWWINEPRICE_FIELD_NUMBER = 3;
    private float newWinePrice_;
    /**
     * <code>optional float newWinePrice = 3;</code>
     */
    public float getNewWinePrice() {
      return newWinePrice_;
    }

    public static final int USERTOKENS_FIELD_NUMBER = 4;
    private java.util.List<com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens> userTokens_;
    /**
     * <code>repeated .UserTokens userTokens = 4;</code>
     */
    public java.util.List<com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens> getUserTokensList() {
      return userTokens_;
    }
    /**
     * <code>repeated .UserTokens userTokens = 4;</code>
     */
    public java.util.List<? extends com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokensOrBuilder> 
        getUserTokensOrBuilderList() {
      return userTokens_;
    }
    /**
     * <code>repeated .UserTokens userTokens = 4;</code>
     */
    public int getUserTokensCount() {
      return userTokens_.size();
    }
    /**
     * <code>repeated .UserTokens userTokens = 4;</code>
     */
    public com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens getUserTokens(int index) {
      return userTokens_.get(index);
    }
    /**
     * <code>repeated .UserTokens userTokens = 4;</code>
     */
    public com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokensOrBuilder getUserTokensOrBuilder(
        int index) {
      return userTokens_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWineIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, wineId_);
      }
      if (!getWineNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, wineName_);
      }
      if (newWinePrice_ != 0F) {
        output.writeFloat(3, newWinePrice_);
      }
      for (int i = 0; i < userTokens_.size(); i++) {
        output.writeMessage(4, userTokens_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWineIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, wineId_);
      }
      if (!getWineNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, wineName_);
      }
      if (newWinePrice_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, newWinePrice_);
      }
      for (int i = 0; i < userTokens_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, userTokens_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent)) {
        return super.equals(obj);
      }
      com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent other = (com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent) obj;

      boolean result = true;
      result = result && getWineId()
          .equals(other.getWineId());
      result = result && getWineName()
          .equals(other.getWineName());
      result = result && (
          java.lang.Float.floatToIntBits(getNewWinePrice())
          == java.lang.Float.floatToIntBits(
              other.getNewWinePrice()));
      result = result && getUserTokensList()
          .equals(other.getUserTokensList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + WINEID_FIELD_NUMBER;
      hash = (53 * hash) + getWineId().hashCode();
      hash = (37 * hash) + WINENAME_FIELD_NUMBER;
      hash = (53 * hash) + getWineName().hashCode();
      hash = (37 * hash) + NEWWINEPRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getNewWinePrice());
      if (getUserTokensCount() > 0) {
        hash = (37 * hash) + USERTOKENS_FIELD_NUMBER;
        hash = (53 * hash) + getUserTokensList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *event that indicates that message was sent to kafka
     * </pre>
     *
     * Protobuf type {@code WinePriceUpdatedWithTokensEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WinePriceUpdatedWithTokensEvent)
        com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.internal_static_WinePriceUpdatedWithTokensEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.internal_static_WinePriceUpdatedWithTokensEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent.class, com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent.Builder.class);
      }

      // Construct using com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserTokensFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        wineId_ = "";

        wineName_ = "";

        newWinePrice_ = 0F;

        if (userTokensBuilder_ == null) {
          userTokens_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          userTokensBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.internal_static_WinePriceUpdatedWithTokensEvent_descriptor;
      }

      public com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent getDefaultInstanceForType() {
        return com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent.getDefaultInstance();
      }

      public com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent build() {
        com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent buildPartial() {
        com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent result = new com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.wineId_ = wineId_;
        result.wineName_ = wineName_;
        result.newWinePrice_ = newWinePrice_;
        if (userTokensBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            userTokens_ = java.util.Collections.unmodifiableList(userTokens_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.userTokens_ = userTokens_;
        } else {
          result.userTokens_ = userTokensBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent) {
          return mergeFrom((com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent other) {
        if (other == com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent.getDefaultInstance()) return this;
        if (!other.getWineId().isEmpty()) {
          wineId_ = other.wineId_;
          onChanged();
        }
        if (!other.getWineName().isEmpty()) {
          wineName_ = other.wineName_;
          onChanged();
        }
        if (other.getNewWinePrice() != 0F) {
          setNewWinePrice(other.getNewWinePrice());
        }
        if (userTokensBuilder_ == null) {
          if (!other.userTokens_.isEmpty()) {
            if (userTokens_.isEmpty()) {
              userTokens_ = other.userTokens_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureUserTokensIsMutable();
              userTokens_.addAll(other.userTokens_);
            }
            onChanged();
          }
        } else {
          if (!other.userTokens_.isEmpty()) {
            if (userTokensBuilder_.isEmpty()) {
              userTokensBuilder_.dispose();
              userTokensBuilder_ = null;
              userTokens_ = other.userTokens_;
              bitField0_ = (bitField0_ & ~0x00000008);
              userTokensBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserTokensFieldBuilder() : null;
            } else {
              userTokensBuilder_.addAllMessages(other.userTokens_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object wineId_ = "";
      /**
       * <code>optional string wineId = 1;</code>
       */
      public java.lang.String getWineId() {
        java.lang.Object ref = wineId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          wineId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string wineId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWineIdBytes() {
        java.lang.Object ref = wineId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wineId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string wineId = 1;</code>
       */
      public Builder setWineId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        wineId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string wineId = 1;</code>
       */
      public Builder clearWineId() {
        
        wineId_ = getDefaultInstance().getWineId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string wineId = 1;</code>
       */
      public Builder setWineIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        wineId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object wineName_ = "";
      /**
       * <code>optional string wineName = 2;</code>
       */
      public java.lang.String getWineName() {
        java.lang.Object ref = wineName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          wineName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string wineName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getWineNameBytes() {
        java.lang.Object ref = wineName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wineName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string wineName = 2;</code>
       */
      public Builder setWineName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        wineName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string wineName = 2;</code>
       */
      public Builder clearWineName() {
        
        wineName_ = getDefaultInstance().getWineName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string wineName = 2;</code>
       */
      public Builder setWineNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        wineName_ = value;
        onChanged();
        return this;
      }

      private float newWinePrice_ ;
      /**
       * <code>optional float newWinePrice = 3;</code>
       */
      public float getNewWinePrice() {
        return newWinePrice_;
      }
      /**
       * <code>optional float newWinePrice = 3;</code>
       */
      public Builder setNewWinePrice(float value) {
        
        newWinePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float newWinePrice = 3;</code>
       */
      public Builder clearNewWinePrice() {
        
        newWinePrice_ = 0F;
        onChanged();
        return this;
      }

      private java.util.List<com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens> userTokens_ =
        java.util.Collections.emptyList();
      private void ensureUserTokensIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          userTokens_ = new java.util.ArrayList<com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens>(userTokens_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokensOrBuilder> userTokensBuilder_;

      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public java.util.List<com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens> getUserTokensList() {
        if (userTokensBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userTokens_);
        } else {
          return userTokensBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public int getUserTokensCount() {
        if (userTokensBuilder_ == null) {
          return userTokens_.size();
        } else {
          return userTokensBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens getUserTokens(int index) {
        if (userTokensBuilder_ == null) {
          return userTokens_.get(index);
        } else {
          return userTokensBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public Builder setUserTokens(
          int index, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens value) {
        if (userTokensBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserTokensIsMutable();
          userTokens_.set(index, value);
          onChanged();
        } else {
          userTokensBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public Builder setUserTokens(
          int index, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder builderForValue) {
        if (userTokensBuilder_ == null) {
          ensureUserTokensIsMutable();
          userTokens_.set(index, builderForValue.build());
          onChanged();
        } else {
          userTokensBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public Builder addUserTokens(com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens value) {
        if (userTokensBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserTokensIsMutable();
          userTokens_.add(value);
          onChanged();
        } else {
          userTokensBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public Builder addUserTokens(
          int index, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens value) {
        if (userTokensBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserTokensIsMutable();
          userTokens_.add(index, value);
          onChanged();
        } else {
          userTokensBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public Builder addUserTokens(
          com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder builderForValue) {
        if (userTokensBuilder_ == null) {
          ensureUserTokensIsMutable();
          userTokens_.add(builderForValue.build());
          onChanged();
        } else {
          userTokensBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public Builder addUserTokens(
          int index, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder builderForValue) {
        if (userTokensBuilder_ == null) {
          ensureUserTokensIsMutable();
          userTokens_.add(index, builderForValue.build());
          onChanged();
        } else {
          userTokensBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public Builder addAllUserTokens(
          java.lang.Iterable<? extends com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens> values) {
        if (userTokensBuilder_ == null) {
          ensureUserTokensIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userTokens_);
          onChanged();
        } else {
          userTokensBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public Builder clearUserTokens() {
        if (userTokensBuilder_ == null) {
          userTokens_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          userTokensBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public Builder removeUserTokens(int index) {
        if (userTokensBuilder_ == null) {
          ensureUserTokensIsMutable();
          userTokens_.remove(index);
          onChanged();
        } else {
          userTokensBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder getUserTokensBuilder(
          int index) {
        return getUserTokensFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokensOrBuilder getUserTokensOrBuilder(
          int index) {
        if (userTokensBuilder_ == null) {
          return userTokens_.get(index);  } else {
          return userTokensBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public java.util.List<? extends com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokensOrBuilder> 
           getUserTokensOrBuilderList() {
        if (userTokensBuilder_ != null) {
          return userTokensBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userTokens_);
        }
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder addUserTokensBuilder() {
        return getUserTokensFieldBuilder().addBuilder(
            com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.getDefaultInstance());
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder addUserTokensBuilder(
          int index) {
        return getUserTokensFieldBuilder().addBuilder(
            index, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.getDefaultInstance());
      }
      /**
       * <code>repeated .UserTokens userTokens = 4;</code>
       */
      public java.util.List<com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder> 
           getUserTokensBuilderList() {
        return getUserTokensFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokensOrBuilder> 
          getUserTokensFieldBuilder() {
        if (userTokensBuilder_ == null) {
          userTokensBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokens.Builder, com.wine.to.up.user.service.api.message.UserTokensOuterClass.UserTokensOrBuilder>(
                  userTokens_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          userTokens_ = null;
        }
        return userTokensBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:WinePriceUpdatedWithTokensEvent)
    }

    // @@protoc_insertion_point(class_scope:WinePriceUpdatedWithTokensEvent)
    private static final com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent();
    }

    public static com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WinePriceUpdatedWithTokensEvent>
        PARSER = new com.google.protobuf.AbstractParser<WinePriceUpdatedWithTokensEvent>() {
      public WinePriceUpdatedWithTokensEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WinePriceUpdatedWithTokensEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WinePriceUpdatedWithTokensEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WinePriceUpdatedWithTokensEvent> getParserForType() {
      return PARSER;
    }

    public com.wine.to.up.user.service.api.message.WinePriceUpdatedWithTokensEventOuterClass.WinePriceUpdatedWithTokensEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WinePriceUpdatedWithTokensEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WinePriceUpdatedWithTokensEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*wine_price_updated_with_tokens_event.p" +
      "roto\032\021user_tokens.proto\"z\n\037WinePriceUpda" +
      "tedWithTokensEvent\022\016\n\006wineId\030\001 \001(\t\022\020\n\010wi" +
      "neName\030\002 \001(\t\022\024\n\014newWinePrice\030\003 \001(\002\022\037\n\nus" +
      "erTokens\030\004 \003(\0132\013.UserTokensB)\n\'com.wine." +
      "to.up.user.service.api.messageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wine.to.up.user.service.api.message.UserTokensOuterClass.getDescriptor(),
        }, assigner);
    internal_static_WinePriceUpdatedWithTokensEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WinePriceUpdatedWithTokensEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WinePriceUpdatedWithTokensEvent_descriptor,
        new java.lang.String[] { "WineId", "WineName", "NewWinePrice", "UserTokens", });
    com.wine.to.up.user.service.api.message.UserTokensOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
